# Generated by Django 5.2.6 on 2025-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('cat', '고양이'), ('dog', '강아지'), ('monkey', '원숭이'), ('dolphin', '돌고래')], default='free', max_length=20, verbose_name='카테고리'),
        ),
    ]
